name: Gradle Package

on:
  [push, workflow_dispatch]

jobs:
  build:

    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write

    steps:
      - name: Checkout sources
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: 17
          distribution: 'temurin'
          server-id: github # Value of the distributionManagement/repository/id field of the pom.xml
          settings-path: ${{ github.workspace }} # location for the settings.xml file

      - name: Get tag or commit id
        id: get-version-id
        uses: iawia002/get-tag-or-commit-id@v1
      - name: Print tag
        run: |
          echo "Tag: ${{ steps.get-version-id.outputs.tag }}"

      - name: Generate changelog
        id: generate_changelog
        run: |
          start_sha=${{ github.event.before }}
          end_sha=${{ github.event.after }}

          if [[ $start_sha != $end_sha ]]; then
            mkdir changelogs
            echo "ChangeLogs:" > CHANGELOGS.txt
            git log --pretty=format:'- [%ad] %s (#%H) by %an' --date=format:'%d-%m-%Y | %I:%M%p' $start_sha..$end_sha >> CHANGELOGS.txt
          fi

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v3

      - name: Execute Gradle build
        run: ./gradlew build

      - name: Release to Github
        id: create_release
        uses: softprops/action-gh-release@v2
        with:
          files: |
            build/libs/**.jar
          token: ${{ secrets.GITHUB_TOKEN }}
          tag_name: ${{ steps.get-version-id.outputs.id }}
          body_path: CHANGELOGS.txt
          draft: false
          prerelease: false
